### ISSUE TITLE
Help with an error message

### ISSUE THREAD

**Issue by thomasbruce** [damianxd/homebridge-vera#16]
Hi
I get this error when home bridge is trying to load the plugin. I'm not that good with linux (homebridge running on raspberry pi. Could use some help :) Thanks!

====================
ERROR LOADING PLUGIN homebridge-vera:
Error: Plugin /usr/local/lib/node_modules/homebridge-vera requires a HomeBridge version of 0.2.13 which does not satisfy the current HomeBridge version of 0.2.16. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:70:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:66:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:24:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:23:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
====================

**Comment by damianxd** [comment]
Hello Thomas

Your homebridge version is an old one, please upgrade it

’’sudo npm install -g homebridge’’



Damian Alarcon / Chief Technology Officer (CTO) 
damian@laerit.dk / +56979982681

Webtjenesten LærIT.dk 
CVR/SE: 29671966 | Ellehammersvej 93, 7500 Holstebro, Danmark 
http://www.laerit.dk

**Comment by thomasbruce** [comment]
aah! Thanks! I'm a real noob at this :)

**Comment by thomasbruce** [comment]
Haha! Now I got this:

====================
ERROR LOADING PLUGIN homebridge-vera:
Error: Plugin /usr/local/lib/node_modules/homebridge-vera requires a HomeBridge version of 0.2.13 which does not satisfy the current HomeBridge version of 0.2.18. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:72:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:68:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:24:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:3)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:397:26)
    at Object.Module._extensions..js (module.js:404:10)
    at Module.load (module.js:343:32)
====================

**Comment by damianxd** [comment]
That's the same error, do a 

’’npm update -g homebridge’’

maybe that will upgrade the homebrige app



Damian Alarcon / Chief Technology Officer (CTO) 
damian@laerit.dk / +56979982681

Webtjenesten LærIT.dk 
CVR/SE: 29671966 | Ellehammersvej 93, 7500 Holstebro, Danmark 
http://www.laerit.dk

**Comment by thomasbruce** [comment]
I tried the npm update -g home bridge but nothing happens. I just takes around 30sec with nothing happening and then it gives me another command line to write on :( don't know what to do next...

Thanks for helping :)

**Comment by damianxd** [comment]
Right now I'm away of any computer since I'm on vacations, but I'll try to get something tomorrow to help you better



Damian Alarcon / Chief Technology Officer (CTO) 
damian@laerit.dk / +56979982681

Webtjenesten LærIT.dk 
CVR/SE: 29671966 | Ellehammersvej 93, 7500 Holstebro, Danmark 
http://www.laerit.dk

**Comment by thomasbruce** [comment]
Thanks!

I tried to reinstall rasbian jessie, homebridge and homebridge-vera but still got the same error...

Everything should be the newest versions...

:(

**Comment by damianxd** [comment]
I'm sorry to hear that... I'm traveling back home tomorrow, so maybe I can give you something better then. For the moment you could edit the package.json file and lower the version of homebridge to whatever version you currently have:

’
  "engines": {
    "homebridge": ">=0.2"
  },’


Damian Alarcon / Chief Technology Officer (CTO) 
damian@laerit.dk / +56979982681

Webtjenesten LærIT.dk 
CVR/SE: 29671966 | Ellehammersvej 93, 7500 Holstebro, Danmark 
http://www.laerit.dk

**Comment by escape89** [comment]
I tried to install today and get the same error.

**Comment by damianxd** [comment]
Sorry for the long wait, should be fixed now. Please try it

**Comment by thomasbruce** [comment]
Thanks for taking the time to help!

After your last message "Sorry for the long wait, it should be fixed now. Please try it" I did a fresh install of raspbian jessie and homebridge + homebridge-vera. I still get the error message:

====================
ERROR LOADING PLUGIN homebridge-vera:
Error: Plugin /usr/local/lib/node_modules/homebridge-vera requires a HomeBridge version of 0.2.13 which does not satisfy the current HomeBridge version of 0.2.19. You may need to upgrade your installation of HomeBridge.
    at Plugin.load (/usr/local/lib/node_modules/homebridge/lib/plugin.js:56:11)
    at Server.<anonymous> (/usr/local/lib/node_modules/homebridge/lib/server.js:77:14)
    at Array.forEach (native)
    at Server._loadPlugins (/usr/local/lib/node_modules/homebridge/lib/server.js:73:22)
    at new Server (/usr/local/lib/node_modules/homebridge/lib/server.js:24:24)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:26:16)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
====================
No plugins found. See the README for information on installing plugins.
Loaded config.json with 0 accessories and 1 platforms.
---
Loading 1 platforms...
/usr/local/lib/node_modules/homebridge/lib/api.js:88
      throw new Error("The requested platform '" + name + "' was not registered by any plugin.");
      ^

Error: The requested platform 'Vera' was not registered by any plugin.
    at API.platform (/usr/local/lib/node_modules/homebridge/lib/api.js:88:13)
    at Server._loadPlatforms (/usr/local/lib/node_modules/homebridge/lib/server.js:201:45)
    at Server.run (/usr/local/lib/node_modules/homebridge/lib/server.js:42:36)
    at module.exports (/usr/local/lib/node_modules/homebridge/lib/cli.js:38:10)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge/bin/homebridge:17:22)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Function.Module.runMain (module.js:447:10)

**Comment by thomasbruce** [comment]
Hi
After looking more closely at the error message it seems to me that I have the newest homebridge version and that it is the hdmebridge-vera plugin that requires and older homebridge version of 0.2.13...so there is nothing I can do until the hdmebridge-vera plugin is updated?

"Plugin /usr/local/lib/node_modules/homebridge-vera requires a HomeBridge version of 0.2.13 which does not satisfy the current HomeBridge version of 0.2.19"

**Comment by harbbyc** [comment]
I have also just tried to install and I am receiving the same message stating that 0.2.13 is needed and i have 0.2.19 is there a solution

**Comment by harbbyc** [comment]
nevermind damianxd was right just change the version in the package file and it will work

**Comment by damianxd** [comment]
Maybe I did something wrong with the publish to NPM, please try it again with this two commands
``npm install -g homebridge``

``npm install -g homebridge-vera``

**Comment by thomasbruce** [comment]
Just tested it and it works :)

Thank you!
